version: "3.8"

services:
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer_db

  flask-mock-server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/customer_db
      DESTINATION__POSTGRES__CREDENTIALS: postgresql://postgres:password@postgres:5432/customer_db
